version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/qredit/client
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install .[test]
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            mkdir test-results
            pytest -v -s --junitxml=test-reports/junit.xml --cov=ark --cov-config=.coveragerc --cov-report xml
      - run:
          name: Codecov
          when: on_success
          command: bash <(curl -s https://codecov.io/bash)
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-reports
          destination: test-reports
